### Site info:
title: 心碎乌托邦的博客
tagline: ELI.ZHANG
author: ELI ZHANG
email: 229828946@163.com
description: "Freshman21 is a Jekyll blog theme." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "心碎乌托邦"
baseurl: "/elizhanght.github.io" # the subpath of your site, e.g. /blog/
url: "http://houshuai.github.io" # the base hostname & protocol for your site
locale: zh-cn

### Personal info and site tools info:
github_username:  elizhanght
favicon:     "/images/20140909195808_4TtP8.jpeg"
aboutme: 技术积累、知识积累 # these are shown on aboutme-sidebar.
aboutme_photo: /images/20140909195808_4TtP8.jpeg# your photo.
google_analytics_key: UA-57979084-1 # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "False" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr) and Russian (ru) 

locales:
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      Google_search: "站内搜索"
      Home: "首页"
      About: "关于"
      Guestbook: "留言"
      Subscribe: "订阅"
    

### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: Elizhang
        href: http://yulijia.net/freshman
        title: Another Jekyll blog theme
      


### Build settings
markdown: kramdown
highlighter: feiendly
kramdown:
        input: GFM
        syntax_highlighter: feiendly
gems: [jekyll-paginate]
paginate: 10
excerpt_separator: <!-- more -->
